// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GramUIClient is the client API for GramUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GramUIClient interface {
	// ListEngineSpecs returns a list of Gram Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (GramUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type gramUIClient struct {
	cc grpc.ClientConnInterface
}

func NewGramUIClient(cc grpc.ClientConnInterface) GramUIClient {
	return &gramUIClient{cc}
}

func (c *gramUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (GramUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &GramUI_ServiceDesc.Streams[0], "/v1.GramUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &gramUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GramUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type gramUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *gramUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gramUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.GramUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GramUIServer is the server API for GramUI service.
// All implementations must embed UnimplementedGramUIServer
// for forward compatibility
type GramUIServer interface {
	// ListEngineSpecs returns a list of Gram Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, GramUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedGramUIServer()
}

// UnimplementedGramUIServer must be embedded to have forward compatible implementations.
type UnimplementedGramUIServer struct {
}

func (UnimplementedGramUIServer) ListEngineSpecs(*ListEngineSpecsRequest, GramUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedGramUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedGramUIServer) mustEmbedUnimplementedGramUIServer() {}

// UnsafeGramUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GramUIServer will
// result in compilation errors.
type UnsafeGramUIServer interface {
	mustEmbedUnimplementedGramUIServer()
}

func RegisterGramUIServer(s grpc.ServiceRegistrar, srv GramUIServer) {
	s.RegisterService(&GramUI_ServiceDesc, srv)
}

func _GramUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GramUIServer).ListEngineSpecs(m, &gramUIListEngineSpecsServer{stream})
}

type GramUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type gramUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *gramUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GramUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GramUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GramUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GramUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GramUI_ServiceDesc is the grpc.ServiceDesc for GramUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GramUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.GramUI",
	HandlerType: (*GramUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _GramUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _GramUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gram-ui.proto",
}
